# Generated by Django 5.2.6 on 2025-09-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeatMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('total_seats', models.IntegerField(default=60)),
                ('filled_seats', models.IntegerField(default=0)),
            ],
        ),
    ]
